### ISSUE TITLE
solid.community -> solidcommunity.net

### ISSUE THREAD

**Issue by scenaristeur** [bourgeoa/solid-file-widget#1]
this widget throw to solid.community

**Comment by bourgeoa** [comment]
@scenaristeur thanks. 
v1.0.0` has been published in `npm`
A new version was needed because v0.4.x were using an outdated version of solid-file-client that included solid-auth-client.

The new version uses only `solid-auth-client` and has an optional parameter to choose an `authorization popupUri`. Default is https://solidcommunity.net/common/popup.html
